[main]
file_path = "default.xex"
patched_file_path = "default_patched.xex"
out_directory_path = "ppc"
switch_table_file_path = "jumptbl.toml"

skip_lr = false
skip_msr = false
ctr_as_local = false
xer_as_local = false
reserved_as_local = false
cr_as_local = false
non_argument_as_local = false
non_volatile_as_local = false

restgprlr_14_address = 0x82C8C460
savegprlr_14_address = 0x82C8C410
restfpr_14_address = 0x82C8F5CC
savefpr_14_address = 0x82C8F580
restvmx_14_address = 0x82C8F2E8
savevmx_14_address = 0x82C8F050
restvmx_64_address = 0x82C8F37C
savevmx_64_address = 0x82C8F0E4

longjmp_address = 0x82C871C0
setjmp_address = 0x82CE0430

invalid_instructions = [
    { data = 0x00485645, size = 0x7BC }, # End of .text section
    { data = 0x82D0A42C, size = 0xC }, # C Specific Frame Handler
    { data = 0x82C8C4B4, size = 0xC }, # C Execute Termination Handler
]

functions = [
    { address = 0x82AA5638, size = 0x11C },
    { address = 0x827CFF70, size = 0x974 },
    { address = 0x827BF530, size = 0x1D4 },
    { address = 0x82807CC8, size = 0x704 },
    { address = 0x82BCD070, size = 0x194 },
    { address = 0x82542418, size = 0x110 },
    { address = 0x823D4008, size = 0x160 },
    { address = 0x82451828, size = 0x58 },
    { address = 0x823D7600, size = 0x55C },
    { address = 0x8240C860, size = 0x104 },
    { address = 0x82607A38, size = 0x7C },
    { address = 0x82942F38, size = 0x5C },
    { address = 0x823D6CB0, size = 0x488 },
    { address = 0x8287D500, size = 0x47C },
    { address = 0x824D66E8, size = 0xFC },
    { address = 0x823D4778, size = 0x104 },
    { address = 0x82430298, size = 0x210 },
    { address = 0x82612C20, size = 0x64 },
    { address = 0x8262EDA0, size = 0x8C },
    { address = 0x8262EE30, size = 0xE8 },
    { address = 0x82B9FB70, size = 0xF0 },
    { address = 0x8287D418, size = 0xE4 },
    { address = 0x8242B368, size = 0xCC },
    { address = 0x82BEDDD8, size = 0x8C },
    { address = 0x82BAAEE8, size = 0xA8 },
    { address = 0x82689630, size = 0xD4 },
    { address = 0x82444830, size = 0x78 },
    { address = 0x828933A0, size = 0x10C },
    { address = 0x82946B18, size = 0xA8 },
    { address = 0x82622BF0, size = 0xB4 },
    { address = 0x824E2C08, size = 0x29C },
    { address = 0x826AC458, size = 0xCC },
    { address = 0x825298F0, size = 0x7C },
    { address = 0x8276EF88, size = 0x134 },
    { address = 0x82956AD8, size = 0x10C },
    { address = 0x82523460, size = 0x174 },
    { address = 0x825EC978, size = 0x80 },
    { address = 0x827AE3E0, size = 0x214 },
    { address = 0x828ADD38, size = 0xDC },
    { address = 0x826228F8, size = 0x2C8 },
    { address = 0x82426478, size = 0x1C8 },
    { address = 0x8295FAA8, size = 0x74 },
    { address = 0x825FD2F8, size = 0x58 },
    { address = 0x828864A0, size = 0x364 },
    { address = 0x8295A8B0, size = 0x134 },
    { address = 0x82822178, size = 0x1AC },
    { address = 0x827CCDD8, size = 0x480 },
    { address = 0x82BA5688, size = 0x94 },
    { address = 0x828FB6C8, size = 0xF4 },
    { address = 0x824E8E78, size = 0x1DC },
    { address = 0x827FF690, size = 0x124 },
    { address = 0x8248AB60, size = 0x7C },
    { address = 0x826347C8, size = 0x7C },
    { address = 0x82326078, size = 0xEC },
    { address = 0x827CD458, size = 0xA4 },
    { address = 0x829428C0, size = 0x70 },
    { address = 0x82946BF0, size = 0xA8 },
    { address = 0x826047E8, size = 0x70 },
    { address = 0x82609350, size = 0xC0 },
    { address = 0x82486C78, size = 0x70 },
    { address = 0x82A2A988, size = 0xF4 },
    { address = 0x8280ED78, size = 0xD8 },
    { address = 0x82863FD0, size = 0x104 },
    { address = 0x82BB09D8, size = 0xE0 },
    { address = 0x829F9780, size = 0x98 },
    { address = 0x82612E38, size = 0x70 },
    { address = 0x82433ED8, size = 0x1B8 },
    { address = 0x82C51FE8, size = 0x150 },
    { address = 0x82C4AE50, size = 0x134 },
    { address = 0x82622700, size = 0x154 },
    { address = 0x8260ABE8, size = 0x64 },
    { address = 0x82A1A220, size = 0x130 },
    { address = 0x82A1DB58, size = 0x270 },
    { address = 0x82946A70, size = 0xA8 },
    { address = 0x829FB5A0, size = 0x94 },
    { address = 0x828FB7C0, size = 0x154 },
    { address = 0x826A60E8, size = 0x60 },
    { address = 0x82424C70, size = 0xB0 },
    { address = 0x82839758, size = 0xF0 },
    { address = 0x82859688, size = 0x80 },
    { address = 0x829477E0, size = 0x84 },
    { address = 0x829A3548, size = 0x2AC },
    { address = 0x82C1BEC8, size = 0xC8 },
    { address = 0x827BD0D8, size = 0x70 },
    { address = 0x8280BA38, size = 0x1B0 },
    { address = 0x8248AC60, size = 0x80 },
    { address = 0x82C3B028, size = 0xA8 },
    { address = 0x82551358, size = 0xA0 },
    { address = 0x82415820, size = 0x17C },
    { address = 0x829501A8, size = 0x8C },
    { address = 0x8265E508, size = 0x200 },
    { address = 0x8248ABE0, size = 0x80 },
    { address = 0x826FE690, size = 0x98 },
    { address = 0x823D3EF0, size = 0x114 },
    { address = 0x8241D4B0, size = 0x58 },
    { address = 0x82634748, size = 0x7C },
    { address = 0x82A00328, size = 0x63C },
    { address = 0x8248ACE0, size = 0x64 },
    { address = 0x827C2DD0, size = 0x130 },
    { address = 0x824159A0, size = 0xF0 },
    { address = 0x8255AC30, size = 0x80 },
    { address = 0x827FFAD0, size = 0xFC },
    { address = 0x827C0C98, size = 0x7C },
    { address = 0x827BCCA8, size = 0x6C },
    { address = 0x82451880, size = 0x5C },
]